<?php $data = array( array("npi_id"=>"1","npi"=>"1.1.1","title"=>"Of the families who are receiving services to become more self-sufficient, the number of families who move up on the FPG scale."),
array("npi_id"=>"2","npi"=>"1.2.1","title"=>"Of the families who are receiving services to become more self-sufficient, the number of families who move to Employment Only or Employment & Other from any other income source category."),
array("npi_id"=>"3","npi"=>"1.2.2","title"=>"Of the families who are receiving services to become more self-sufficient, the number of families who report a decrease in reliance on cash assistance or public benefits because they are able to meet family needs without these supports."),
array("npi_id"=>"4","npi"=>"1.3.1a","title"=>"The number of individuals who were unemployed and obtained a job or become self employed."),
array("npi_id"=>"5","npi"=>"1.3.1b","title"=>"The number of individuals who were employed and improved employment benefits"),
array("npi_id"=>"6","npi"=>"1.3.1c","title"=>"The number of individuals who were employed and maintained a job for at least 90 days"),
array("npi_id"=>"7","npi"=>"1.3.2a","title"=>"The number of individuals who obtained reliable transportation)"),
array("npi_id"=>"8","npi"=>"1.3.2b","title"=>"The number of individuals who obtained drivers license"),
array("npi_id"=>"9","npi"=>"1.3.3a","title"=>"The number of families who obtained health care services"),
array("npi_id"=>"10","npi"=>"1.3.3b","title"=>"The number of families who secured health care insurance"),
array("npi_id"=>"11","npi"=>"1.3.4a","title"=>"The number of homeless or near homeless families who obtained safe and affordable housing"),
array("npi_id"=>"12","npi"=>"1.3.4b","title"=>"The number of families who maintained safe and affordable housing for 90 days."),
array("npi_id"=>"13","npi"=>"1.3.4c","title"=>"The number of families who achieved home ownership"),
array("npi_id"=>"14","npi"=>"1.3.5b","title"=>" Number of families who obtained court-ordered child support payments and the expected annual aggregated dollar amount of payments"),
array("npi_id"=>"15","npi"=>"1.3.5c","title"=>"Number of families in tax preparation programs who applied for any type of Federal or State tax credit and the expected aggregate dollar amount of credits"),
array("npi_id"=>"16","npi"=>"1.3.5d","title"=>"Number of individuals who increased savings through an Individual Development Account (IDA) or other savings account"),
array("npi_id"=>"17","npi"=>"1.3.6a","title"=>"The number of individuals who obtained skills/competencies required for employment"),
array("npi_id"=>"18","npi"=>"1.3.6b","title"=>"The number of individuals who improved basic or secondary academic skills (ABE or GED) and received certificate or diploma"),
array("npi_id"=>"19","npi"=>"1.3.6c","title"=>"The number of individuals who completed postsecondary education program and obtained certificate or diploma"),
array("npi_id"=>"20","npi"=>"1.3.7a","title"=>"The number of parents and other adults who learn and exhibit improved parenting skills"),
array("npi_id"=>"21","npi"=>"1.3.7b","title"=>"The number of parents and other adults who obtained skills/competencies required for family functioning (i.e. nutrition, housing, cleanliness, etc.)"),
array("npi_id"=>"22","npi"=>"2.1.1","title"=>"DEVELOPMENTAL ASSETS Ìê These are assets that allow residents to attain the skills needed to be successful in all aspects of daily life (e.g., educational institutions, early learning centers, and health resources)."),
array("npi_id"=>"23","npi"=>"2.1.1a","title"=>"Accessible and affordable health care services/facilities created"),
array("npi_id"=>"24","npi"=>"2.1.1b","title"=>"Accessible and affordable health care services/facilities saved from reduction or elimination"),
array("npi_id"=>"25","npi"=>"2.1.1c","title"=>"Accessible safe and affordable child care or child development placement opportunities created"),
array("npi_id"=>"26","npi"=>"2.1.1d","title"=>"Accessible safe and affordable child care or child development placement opportunities saved from reduction or elimination"),
array("npi_id"=>"27","npi"=>"2.1.1e","title"=>"Accessible before-school and after-school program placement opportunities created"),
array("npi_id"=>"28","npi"=>"2.1.1f","title"=>"Accessible before-school and after-school program placement opportunities saved from reduction or elimination"),
array("npi_id"=>"29","npi"=>"2.1.1g","title"=>"Accessible educational and training placement opportunities created, including vocational, literacy, and life skill training, ABE/GED, and postsecondary education"),
array("npi_id"=>"30","npi"=>"2.1.1h","title"=>"Accessible educational and training placement opportunities saved from reduction or elimination, including vocational, literacy, and life skill training, ABE/GED, and postsecondary education"),
array("npi_id"=>"31","npi"=>"2.1.2","title"=>"COMMERCIAL ASSETS Ìê These assets are associated with production, employment, transactions, and sales (e.g., labor force and retail establishments)."),
array("npi_id"=>"32","npi"=>"2.1.2a","title"=>"Increase in the availability of commercial services within low-income neighborhoods"),
array("npi_id"=>"33","npi"=>"2.1.2b","title"=>"Preservation of commercial services within low-income neighborhoods"),
array("npi_id"=>"34","npi"=>"2.1.3","title"=>"RECREATIONAL ASSETS Ìê These assets create value in a neighborhood beyond work and education (e.g., parks, open space, community gardens, and arts organizations)."),
array("npi_id"=>"35","npi"=>"2.1.3a","title"=>"Increase in the availability of community facilities"),
array("npi_id"=>"36","npi"=>"2.1.3b","title"=>"Preservation of community facilities"),
array("npi_id"=>"37","npi"=>"2.1.3c","title"=>"Increase in neighborhood quality-of-life resources"),
array("npi_id"=>"38","npi"=>"2.1.3d","title"=>"Preservation of neighborhood quality-of-life resources"),
array("npi_id"=>"39","npi"=>"2.1.4","title"=>"PHYSICAL ASSETS - These assets are associated with the built environment and physical infrastructure (e.g., housing, commercial buildings, and roads)."),
array("npi_id"=>"40","npi"=>"2.1.4a","title"=>"Safe and affordable housing units created in the community"),
array("npi_id"=>"41","npi"=>"2.1.4b","title"=>"Safe and affordable housing units improved in the community through construction, weatherization or rehabilitation achieved by Community Action activity or advocacy"),
array("npi_id"=>"42","npi"=>"2.1.4c","title"=>"Accessible new transportation resources, including public or private transportation"),
array("npi_id"=>"43","npi"=>"2.1.4d","title"=>"Accessible expanded transportation resources, including public or private transportation"),
array("npi_id"=>"44","npi"=>"2.1.4e","title"=>"Accessible transportation resources saved from reduction or elimination, including public or private transportation"),
array("npi_id"=>"45","npi"=>"2.1.5","title"=>"SOCIAL ASSETS - These assets establish well-functioning social interactions (e.g., public safety)."),
array("npi_id"=>"46","npi"=>"2.1.5a","title"=>"Increase in the availability of community services to improve public health and safety"),
array("npi_id"=>"47","npi"=>"2.1.5b","title"=>"Preservation of community services to improve public health and safety"),
array("npi_id"=>"48","npi"=>"3.1.1","title"=>"Number of low-income people participating in formal community organizations, government, boards, or councils that provide input to decision-making through Community Action efforts"),
array("npi_id"=>"49","npi"=>"3.1.2","title"=>"Number of low-income people engaged in non-governance community activities or groups created or supported by Community Action"),
array("npi_id"=>"50","npi"=>"3.2.1","title"=>"Number of individuals with low incomes who report an increase in social network connections as a result of participation in community activities"),
array("npi_id"=>"51","npi"=>"3.2.2","title"=>"Number of volunteer hours donated to the agency by low-income Community Action program participants"),
array("npi_id"=>"52","npi"=>"4.1.1","title"=>"Number of organizations, both public and private, that Community Action actively works with to expand resources and opportunities in order to achieve family and community outcomes."),
array("npi_id"=>"53","npi"=>"4.1.1a","title"=>"4.1.1 TEXT NARRATIVE"),
array("npi_id"=>"54","npi"=>"4.2.1","title"=>"Number of services that are available to Community Action Agency customers because of partnerships"),
array("npi_id"=>"55","npi"=>"4.2.2","title"=>"Number of volunteer hours donated to the agency by the public"),
array("npi_id"=>"56","npi"=>"5.1.1","title"=>"Staff, volunteers, and board members have the skills required to achieve results as measured by having credentials and/or nationally recognized certifications."),
array("npi_id"=>"57","npi"=>"5.1.2","title"=>"The number of Organizational Standards met by the CAA"),
array("npi_id"=>"58","npi"=>"6.1.1","title"=>"The number of individuals who receive temporary emergency assistance "),
array("npi_id"=>"59","npi"=>"6.1.1a","title"=>"The number of individuals who receive emergency food"),
array("npi_id"=>"60","npi"=>"6.1.1b","title"=>"The number of individuals who receive emergency fuel or utility payments funded by LIHEAP or other public and private funding sources"),
array("npi_id"=>"61","npi"=>"6.1.1c","title"=>"The number of individuals who receive emergency rent or mortgage assistance"),
array("npi_id"=>"62","npi"=>"6.1.1d","title"=>"The number of individuals who receive emergency temporary shelter"),
array("npi_id"=>"63","npi"=>"6.1.1e","title"=>"The number of individuals who receive assistance in other emergency situations"),
array("npi_id"=>"64","npi"=>"6.1.2","title"=>"Number of Rides Provided"),
array("npi_id"=>"65","npi"=>"6.1.3","title"=>"Number of Information and Referral Calls"),
array("npi_id"=>"66","npi"=>"6.2.1","title"=>"The number of families who report receipt of new benefits to stabilize the family "),
array("npi_id"=>"67","npi"=>"6.2.2","title"=>"The number of families who move from no income to another income category"),
array("npi_id"=>"68","npi"=>"6.3.1","title"=>"The number of children who increase school readiness"),
array("npi_id"=>"69","npi"=>"6.3.2","title"=>"The number of children and youth achieve or improve school success"),
array("npi_id"=>"70","npi"=>"6.3.3","title"=>"The number of families for whom safe, high quality care was obtained for children or other dependents"),
array("npi_id"=>"71","npi"=>"6.3.4","title"=>"The number of seniors who maintain maximum feasible independence"),
array("npi_id"=>"72","npi"=>"6.3.5","title"=>"The number of Individuals with disabilities who maintain maximum feasible independence and productivity"),
array("npi_id"=>"73","npi"=>"6.4.1","title"=>"The number of families who report they have become more stable through services of the CAA or through referrals for service "),
array("npi_id"=>"74","npi"=>"6.4.2","title"=>"The number of families who have entered a self-sufficiency program") );
?>